name: Auto Commit

on:
  schedule:
    - cron: '0 3 * * *'  # 10h sáng Việt Nam mỗi ngày
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update timestamp
        run: echo "Auto commit at $(date)" >> log.txt

      - name: Setup Git config
        run: |
          git config user.name "duyseetinh2k3"
          git config user.email "duyseetinh2k3@gmail.com"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Auto commit on $(date)" || echo "No changes to commit"
          git push
